dist: bionic
language: go

services:
  - docker

go:
  - 1.14.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

go_import_path: github.com/rcperlin/rds_exporter

env:
  global:
    # AWS - PMM Autotest account.
    # Travis secrets are not exposed to pull requests from forks: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
    - AWS_ACCESS_KEY=AKIAZPBRO3QWGCO72MJZ
    - secure: "X8jXCbsnCkyEsZN11AQ5NgF5Wl84ZTWxr8LuWXgVZ/3QwRvY7rK25FZVwf8TQqF3wch92WFnSwF9jQ37cz0H6SOa+tQ0NHDhUGIqEfdIlIfb8lGvEEPsD3OPenqRZWDRFFoywgkqu+PZU2uuFW5gC93RbClgBGv4oy+NrJF+Etkikv6E+mMZQc0O/UtEZUyXvRnfKY0/zPAHPsSNtEBvk3Q2lAIsl31pfMn6m1rBxPmuHShsigo+smMZTGXkijIa/aXUNOxz5lXppjvMmbNAg4/3+46MHTDXLmX7irGaUMvKKi4Ya6Hvu9+6UGjInrothVN98Y2k2J+ERZooM7ND7kv3vn3RilYbBhnpsdmmpL0nEQYTsJBvaaWKRZMIxS0Xd21CKOSGN+8Omq9iBgiW1L87xKxYD78OF+2Z9VwzHHk+Oaq2ky3LT/z3WGtnMWpURSxvjw76neFIxoIMHFVIZh0kywrmObZy3mgF0zzC/jRU2PK/ie9k0LJhxuHoEeb4b55f1PmUfhCJ7KblE3x13SlUUQqnvIL7qscKL1nEtFl/kidHtBYJAZzi0ctb2mHduzi89VYKqu6w3S93HpQQLkqpg9+i+i890mQrpytFGrcGVj4SikIE1fwlv/V8MS9zZukvizSV9l/Z0hV5YDqqHPX0UICrf7w/u9vkZSsz45g="
    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: "2BgdTQdJFrXJANqhgOHOTZBL4F8kh1WxoYlG0pMKam7VWooaSiehc18abODUmRkdVoDPen1MpikmAH8ekabkTfkAJ+qxqEUp1pkA20bs18tePUyHS2iGn5hgN9SMrxOb5QB0vHilg0B95BNlIy2kZY6A2+JWn73aqDsFDMV8OMEeA4Mi0KnYtbXmmZ9gqTw+gusfxkVD8RNgXvg4zGmNLS/hLaXFFtmtx9xl7SAbQPvxtj9Po7FUYq9G+qazjg0pRZ9UH6hJQPxIHOumRx447hagL/521X9ZAtlwe17H368M4a7J2Cd6Tm70alktDH3Tsu258PMsKsTqQOHtMOfeOiDshqN2K0AuKatYBsSAshxgDChDe7+Wyi9VV1mlo1zUTEe4bVaBlHZy0VCy5JuzwrxFS2Xz/dXvNIaqlTfzimrPgOavXREDycoKHpcJf6IKvwWX9+JVopTqR7Md3gQIOpRrLJ2wOtAv8KdG6g2wuBe2IMdbXpUOPvBS+SjERuXAp99H4H2irt74HAfTudtvC6MtE/t5BYV4hmuEfX5zKGiZ6xShBasQeRWqsSwi4gWU8k5CpwqbkMt4NMNBWGZuAi01w8fM0QHidqlBOO4drps0N1gbNXUIgR/0S1w8rYzfL4Z2K7bX7L9qYyP09dSeha3MUFiu0w4WCNqPoafYiQo="

install:
  # install reviewdog and golangci-lint
  - curl https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
  - curl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

script:
  - make travis
